### ISSUE TITLE
xlsx' bug

### ISSUE THREAD

**Issue by jayzh1010** [jazzband/tablib#212] opened 2015-11-18 01:54 UTC
my Python version is 2.7;
'11111111111111111111' or 11111111111111111111 both will truncated to 11111111111111100000;
maybe the openpyxl in you package has something wrong;
when i use the latest official openpyxl, '11111111111111111111' will not be truncated;

**Comment by kennethreitz** [comment] 2016-02-07 12:12
This is because our openpyxl needs to be updated.

**Comment by kennethreitz** [comment] 2016-02-07 12:31
#197 is the same bug.

**Comment by jayzh1010** [comment] 2016-02-24 10:13
when will u fix this bug? tks

**Comment by YiuTerran** [comment] 2016-05-12 03:37
still not fixed? So...Should I use openpyxl instead?

**Comment by jayzh1010** [comment] 2016-05-22 08:09
@YiuTerran i think u should use openpyxl and encapsulate it.

**Comment by hugovk** [comment] 2019-10-19 13:01
Retesting:

* Python 3.7.4
* tablib==0.14.0 (newest)
* openpyxl==3.0.0 (newest)

```python
import tablib

data = tablib.Dataset()
data.headers = ["test_id"]

a = "11111111111111111111"
b = 11111111111111111111
data.append([a])
data.append([b])
with open("test.xls", "wb") as f:
    f.write(data.xls)
```


test.xls contains:

```
test_id
11111111111111111111
11111111111111100000
```

The string matches the input, but not the integer. Closing as a duplicate of #197.

**Closed by hugovk** 2019-10-19 13:01 UTC
Labels: bug
