### ISSUE TITLE
Tablib fails to import dates from xlsx

### ISSUE THREAD

**Issue by isedwards** [jazzband/tablib#373] opened 2019-08-11 09:19 UTC
Given an Excel xlsx file containing:

| Integer | String | Float  | Date           |
|---------:|-------|-------:|--------------|
|          1 | abc     |   1.2   | 10/08/2019 |

OpenPyXL makes some sensible choices on data types:
```
import openpyxl
wb = openpyxl.load_workbook(filename = 'tablib_test.xlsx')
[cell.value for cell in wb.active[2]]
```
> [1L, u'abc', 1.2, datetime.datetime(2019, 8, 10, 0, 0)]

However, tablib ends up with Excel's internal date format representation and, as far as I can see, there is no way to detect that this data was originally a date:
```
import tablib
data = tablib.Dataset().load(open('tablib_test.xlsx').read())
data[0]
```
> (1.0, u'abc', 1.2, 43687.0)

Tested with tablib 0.13.0 and 0.12.1

**Comment by vinayak-mehta** [comment] 2019-08-27 18:24
Let me reproduce this over the weekend.

**Comment by isedwards** [comment] 2019-09-08 19:27
I've had to abandon tablib completely :'(

**Comment by vinayak-mehta** [comment] 2019-10-03 06:03
I'm sorry to hear that, and for not being able to spend time here. I'm transferring it to Jazzband where people who can spend time maintaining it can do so!

**Comment by claudep** [comment] 2019-10-04 18:46
While debugging this, I noticed the problem was bad format detection. Tablib detects your xlsx file as xls (handled by xlrd). So if you specified the `format='xlsx'` parameter of the load method, it would have worked probably.

**Closed** 2019-10-04 18:46 UTC

**Comment by MicBoucinha** [comment] 2020-03-06 17:35
Hi, regarding this issue, I am also having it.

I have an xlsx file with dates and I can confirm that the values are kept with Excel's internal date.
I am loading the file with:
```python
with open(filepath, "rb") as f:
    dataset = tablib.import_set(f.read(), format='xlsx')
```
tablib version: 1.1.0
openpyxl: 3.0.3

Anyone can confirm this?
Thanks!

**Comment by claudep** [comment] 2020-03-06 19:38
I would need an example file to be able to reproduce. It may be related to some custom date format.

**Comment by MicBoucinha** [comment] 2020-03-09 10:55
Apologies, I confused the issue that I am having with XLS files (and not XLSX files as I mentioned).

I attached the XLS with the simple example where the result from loading it with `format='xls'` in the `import_set` function

    dataset._data
    [[225.0, 'TEST_SWP_02', 43392.60439814815, 43507.46597222222, '']]

For the XLSX file I have the expected output for the dates, although I have several extra None values.

    dataset._data
    [[225, 'TEST_SWP_02', datetime.datetime(2018, 10, 19, 14, 30, 20), datetime.datetime(2019, 2, 11, 11, 11), None, None, None, None, None, None, None, None, None, None]]

I can open a new issue if you prefer.

[example_dates.zip](https://github.com/jazzband/tablib/files/4306183/example_dates.zip) (had to be in zip form since GitHub won't accept .xls files, only .xlsx).

Thank you.
