### ISSUE TITLE
Generated XLSX files aren't valid XML when data includes escape sequences

### ISSUE THREAD

**Issue by longhotsummer** [jazzband/tablib#249] opened 2016-08-10 08:59 UTC
If a value such as `^D` is written as XLSX, invalid XML is generated and Excel complains. Excel's error: `Removed Part: /xl/sharedStrings.xml with XML error.  (Strings) Illegal xml character. Line 1, column 115.`

To reproduce:

``` python
import tablib
data = tablib.Dataset(headers=['test'])
data.append(['^D'])
with open('out.xlsx', 'wb') as f:
    f.write(data.xlsx)
```

Then try to open the file in Excel.

**Comment by hugovk** [comment] 2019-10-22 15:16
Cannot reproduce.

This is now working with Python 3.7.4, Tablib 0.14.0, openpyxl 3.0.0, Excel for Mac 16.30:

![image](https://user-images.githubusercontent.com/1324225/67301402-02f22080-f4f8-11e9-963e-9328886d7e77.png)

**Comment by hugovk** [comment] 2019-10-22 15:20
Closing as the original issue is quite old. Please comment if this is still a problem and we can re-open 👍

**Closed by hugovk** 2019-10-22 15:20 UTC
