### ISSUE TITLE
Export is improper in xlsx format, but is proper in xls.

### ISSUE THREAD

**Issue by noodlebreak** [jazzband/tablib#284] opened 2017-04-10 06:32 UTC
Column headings go missing, column data goes missing.
But if exported in `xls` format, it's all perfect. Now the problem with `xls` format is that it doesn't support more than 256 columns, which is why we don't use it.

Also, this is happening with a specific set of data, but I'm not at the liberty to share the excel which caused this, as it belongs to a client. What could be the problem?

**Comment by noodlebreak** [comment] 2017-04-10 11:39
I debugged and found that this is happening:

Till the moment the excel workbook is converted into BytesIO stream object (in `formats._xlsx.export_book`), all is well.
The excel generated on saving the stream gives a bad excel.


    > /home/ash/.virtualenvs/matrix/local/lib/python2.7/site-packages/tablib/formats/_xlsx.py(64)export_book()
         63     stream = BytesIO()
    ---> 64     wb.save(stream)
         65     return stream.getvalue()

    ipdb> 
    > /home/ash/.virtualenvs/matrix/local/lib/python2.7/site-packages/tablib/formats/_xlsx.py(65)export_book()
         64     wb.save(stream)
    ---> 65     return stream.getvalue()
         66 

    ipdb> '|'.join([err.value for err in wb.worksheets[0].rows[0]])
    u'#|Do NOT edit or delete this column (DB_ID_LIST)|Title|Description|Price|Stock|Category|Featured|Active|COD|Bank|SKU|Short Description|Image1|Image2|Image3|Image4|Image5|Image6|Image7|Image8|Image9|Image10|Discount Price|Variant Option1 Name|Variant Option2 Name|Any Other variant(if required)|Is Default Variant|Length|Breadth|Height|Weight|Sort Order|General:Material|General:Volume Capacity'
    ipdb> 


All column headers are valid and present till here. But on saving the stream to file on disk, (or writing to a Django HttpResponse object, as a download), some columns go missing:

    #   Do NOT edit or delete this column (DB_ID_LIST)  Title   Description Price   Stock       Featured        COD Bank    SKU Short Description   Image1      Image3  Image4      Image6  Image7  Image8  Image9  Image10 Discount Price      Variant Option2 Name            Length  Breadth Height      Sort Order  General:Material    General:Volume Capacity

**Comment by iurisilvio** [comment] 2017-04-10 13:40
Are you able to reproduce it with other data? I use `xlsx` export all the time and never had this issue. I need  some example reproducing the problem.

Based on your debbugging, looks like it is an `openpyxl` issue.

**Comment by noodlebreak** [comment] 2017-04-11 07:22
@iurisilvio No, as I mentioned in the first post, this is specific to the bunch of data that's exported.

**Comment by claudep** [comment] 2019-10-04 19:44
I'm afraid that without real data to reproduce the issue, and failing some demonstration that tablib is at fault, we have no choice but to close the issue. Feel free to reopen if you can give us data to reproduce.

**Closed by claudep** 2019-10-04 19:44 UTC
